apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-arena
  namespace: load-arena
spec:
  ingressClassName: nginx
  rules:
    - host: load-arena.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: load-arena
                port:
                  number: 80
