apiVersion: v1
kind: Service
metadata:
  name: load-arena
  namespace: load-arena
  labels:
    app: load-arena
spec:
  selector:
    app: load-arena
  ports:
    - name: http
      port: 80
      targetPort: http
