apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-arena
  namespace: load-arena
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: load-arena
  namespaceSelector:
    matchNames:
      - load-arena
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
